### ISSUE TITLE
[feature] Consider auto converting dict into Dict on Dict.__setattr__

### ISSUE THREAD

**Issue by Jean-Daniel** [kapicorp/kadet#2]
This is just a suggestion, but I think it would be convenient to automatically convert `dict` into `Dict` when setting a property.

```python
    def __setattr__(self, name, value):
        if type(value) == dict:
            value = Dict(from_dict=value)
        return self.__setitem__(name, value)
```

This would make this code valid:

```python
obj = kadet.BaseObj()
# would works too with this change
obj.root.hello = "world"
obj.root.labels = {"name": "name", "value": "value"}
obj.root.labels.other = "other" # fails without this change as labels would be a dict and not a Dict
```

I suggest using `type(value) == dict` to avoid converting a special kind of dict (defaultdict, …) if the user chooses to use one explicitly.

**Comment by ramaro** [comment]
Great idea! Feel free to send a PR. Thanks @Jean-Daniel

**Comment by ramaro** [comment]
Done in #4
